### ISSUE TITLE
Allow custom Backend Servers

### ISSUE THREAD

**Issue by Aradiv** [wasabee-project/Wasabee-Mobile-Xamarin#30]
currently the backend servers are harcoded in the App.

It would be great to have a link on the custom backend servers that allows to register the backend server so it can be used in the App.

1. register intent for something like `*/register_server.wasabee`
2. the backend server provides the required data (url, name, public key for oauth etc)
3. App allows the newly added server to be used as backend server
4. custom added servers can be removed from the app

**Comment by SebastienForay** [comment]
Hi @Aradiv !

Are you already running your own Wasabee Server ?

**Comment by Aradiv** [comment]
currently in the process of setting things up. (mostly for development purpose to try things out)

**Comment by SebastienForay** [comment]
Started work on https://github.com/wasabee-project/Wasabee-Mobile-Xamarin/tree/dev/custom_backend_server for Wasabee backend development purposes, but this will be used for this feature request when ready
