### ISSUE TITLE
Checklist : Agent can't claim unassigned assignments

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-Mobile-Xamarin#8]
API needed (@cloudkucooland)

UI update : add claim button in assignments details popup
Button available only for unassigned things

**Comment by cloudkucooland** [comment]
/draw/{id}/marker/{id}/claim" ("POST")

is ready for testing on the test server

**Comment by cloudkucooland** [comment]
/draw/{id}/link/{id}/reject ("POST")
/draw/{id}/link/{id}/claim ("POST")

both ready for testing
